
debug: true,

# dryRun: true,
#         "@semantic-release/changelog": "5.0.1",
#         "@semantic-release/git": "9.0.3",

# verifyConditions:
# 	- "@semantic-release/changelog"
# 	- "@semantic-release/npm"
# 	- "@semantic-release/github"
# prepare:
# 	- "@semantic-release/changelog"
# 	- "@semantic-release/npm"
# 	- "@semantic-release/git"

# publish:
# 	- "@semantic-release/npm"
# 	- "@semantic-release/github"
# success:
# 		"@semantic-release/github"
# preset: "angular"
