name: Node

on:
  push:
    branches:
    - main
    - ci/**
  pull_request:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ga-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16, 17, 18 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version
        node-version: ${{ matrix.node-version }}
        check-latest: true
        cache: 'npm'

    - run: npm ci

    - run: npm test

    - run: npm run lint
